export const CATEGORIES = {
  'Latest AI News': [
    'artificial intelligence', 'openai', 'anthropic', 'google deepmind', 'meta ai',
    'mistral', 'xai', 'grok', 'chatgpt', 'claude', 'gemini', 'llama', 'gpt',
    'foundation model', 'generative ai', 'large language model', 'transformer',
    'multimodal', 'text-to-image', 'text-to-speech', 'diffusion', 'stable diffusion',
    'midjourney', 'dall-e', 'speech', 'voice', 'audio', 'regulation', 'policy',
    'ai safety', 'alignment', 'governance', 'funding', 'startup', 'acquisition',
    'investment', 'chip', 'gpu', 'nvidia', 'tpu', 'h100', 'compute', 'hardware',
    'robotics', 'robot', 'humanoid', 'open source', 'hugging face', 'benchmark',
    'sota', 'state-of-the-art',
  ],

  'AI Agents': [
    'agent', 'agentic', 'multi-agent', 'autonomous agent', 'ai agent',
    'langchain', 'langgraph', 'autogen', 'crewai', 'llamaindex',
    'rag', 'retrieval-augmented generation', 'retrieval augmented',
    'function calling', 'tool use', 'tool calling', 'skills', 'plugin',
    'agent framework', 'agentic workflow', 'orchestration', 'planner',
    'memory', 'reflection', 'react agent', 'chain-of-thought', 'reasoning',
    'planning agent', 'coding agent', 'browser agent', 'computer use',
    'swarm', 'agent loop', 'mcp', 'model context protocol',
    'build an agent', 'agent tutorial', 'agent guide', 'semantic kernel',
    'cohere', 'embeddings tutorial', 'vector search tutorial',
    'how to build', 'step by step', 'getting started with agents',
  ],

  'Digital Twin': [
    'digital twin', 'digital twins','digital twin resource', 'cyber-physical', 'virtual model',
    'physics simulation', 'physics-based', 'sim-to-real', 'industrial simulation',
    'digital replica', 'synthetic data', 'virtual environment',
    'nvidia omniverse', 'omniverse', 'azure digital twins', 'azure adt',
    'smart city', 'smart cities', 'smart building', 'smart airport',
    'smart mall', 'industrial iot', 'iiot', 'factory simulation',
    'building information modeling', 'bim', 'industry 4.0', 'industrial metaverse',
    'predictive maintenance', 'asset monitoring', 'digital thread',
    'urban simulation', 'infrastructure simulation',
  ],

  'Data Science': [
    'data science', 'data scientist', 'data analysis', 'data analytics',
    'python', 'pandas', 'numpy', 'matplotlib', 'seaborn', 'plotly',
    'jupyter', 'notebook', 'google colab', 'kaggle', 'dataset',
    'feature engineering', 'exploratory data analysis', 'eda',
    'statistics', 'statistical', 'probability', 'regression',
    'visualization', 'dashboard', 'tableau', 'power bi',
    'sql', 'dbt', 'spark', 'databricks', 'data pipeline',
    'data engineer', 'data career', 'course', 'tutorial', 'bootcamp',
    'learn data science', 'data science course',
    'beginner guide', 'step-by-step', 'how to', 'introduction to',
    'complete guide', 'python tutorial', 'data cleaning', 'data wrangling',
    'machine learning tutorial', 'scikit', 'model evaluation',
    'freecodecamp', 'datacamp', 'real python', 'cheatsheet',
  ],

  'Machine Learning': [
    'machine learning', 'deep learning', 'neural network',
    'pytorch', 'tensorflow', 'keras', 'scikit-learn', 'sklearn', 'xgboost',
    'model training', 'fine-tuning', 'transfer learning', 'pretraining',
    'model deployment', 'mlops', 'model serving',
    'gradient descent', 'backpropagation', 'loss function', 'optimizer',
    'convolutional', 'cnn', 'recurrent', 'lstm', 'attention mechanism',
    'embedding', 'vector database', 'onnx', 'model compression',
    'quantization', 'pruning', 'distillation', 'federated learning',
    'reinforcement learning', 'reward model', 'rlhf',
    'ml for digital twins', 'predictive model', 'classification',
    'clustering', 'anomaly detection',
    'learn machine learning', 'ml tutorial', 'ml guide', 'fast.ai',
    'weights biases', 'wandb', 'paperspace', 'colab tutorial',
    'build a model', 'train a model', 'ml from scratch', 'beginner ml',
    'intermediate ml', 'advanced ml', 'ml project', 'hands-on',
  ],
};

export const ALL_CATEGORIES = Object.keys(CATEGORIES);
